server:
  port: 9002
  servlet:
    context-path: /api/storage

spring:
  application:
    name: m-storage
  data:
    mongodb:
      uri: ${DB_URI}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9101/eureka